#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Turnos")]
	public partial class DC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEspecialidade(Especialidade instance);
    partial void UpdateEspecialidade(Especialidade instance);
    partial void DeleteEspecialidade(Especialidade instance);
    partial void InsertTurno(Turno instance);
    partial void UpdateTurno(Turno instance);
    partial void DeleteTurno(Turno instance);
    partial void InsertEspecialidad_Medico(Especialidad_Medico instance);
    partial void UpdateEspecialidad_Medico(Especialidad_Medico instance);
    partial void DeleteEspecialidad_Medico(Especialidad_Medico instance);
    partial void InsertMedico(Medico instance);
    partial void UpdateMedico(Medico instance);
    partial void DeleteMedico(Medico instance);
    partial void InsertMedicoxDia(MedicoxDia instance);
    partial void UpdateMedicoxDia(MedicoxDia instance);
    partial void DeleteMedicoxDia(MedicoxDia instance);
    partial void InsertObraSocial_TipoTurno(ObraSocial_TipoTurno instance);
    partial void UpdateObraSocial_TipoTurno(ObraSocial_TipoTurno instance);
    partial void DeleteObraSocial_TipoTurno(ObraSocial_TipoTurno instance);
    partial void InsertObrasSociale(ObrasSociale instance);
    partial void UpdateObrasSociale(ObrasSociale instance);
    partial void DeleteObrasSociale(ObrasSociale instance);
    partial void InsertPaciente(Paciente instance);
    partial void UpdatePaciente(Paciente instance);
    partial void DeletePaciente(Paciente instance);
    partial void InsertTipoTurno(TipoTurno instance);
    partial void UpdateTipoTurno(TipoTurno instance);
    partial void DeleteTipoTurno(TipoTurno instance);
    #endregion
		
		public DC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Especialidade> Especialidades
		{
			get
			{
				return this.GetTable<Especialidade>();
			}
		}
		
		public System.Data.Linq.Table<Turno> Turnos
		{
			get
			{
				return this.GetTable<Turno>();
			}
		}
		
		public System.Data.Linq.Table<Especialidad_Medico> Especialidad_Medicos
		{
			get
			{
				return this.GetTable<Especialidad_Medico>();
			}
		}
		
		public System.Data.Linq.Table<Medico> Medicos
		{
			get
			{
				return this.GetTable<Medico>();
			}
		}
		
		public System.Data.Linq.Table<MedicoxDia> MedicoxDias
		{
			get
			{
				return this.GetTable<MedicoxDia>();
			}
		}
		
		public System.Data.Linq.Table<ObraSocial_TipoTurno> ObraSocial_TipoTurnos
		{
			get
			{
				return this.GetTable<ObraSocial_TipoTurno>();
			}
		}
		
		public System.Data.Linq.Table<ObrasSociale> ObrasSociales
		{
			get
			{
				return this.GetTable<ObrasSociale>();
			}
		}
		
		public System.Data.Linq.Table<Paciente> Pacientes
		{
			get
			{
				return this.GetTable<Paciente>();
			}
		}
		
		public System.Data.Linq.Table<TipoTurno> TipoTurnos
		{
			get
			{
				return this.GetTable<TipoTurno>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Especialidades")]
	public partial class Especialidade : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _especialidad_id;
		
		private string _especialidad_nombre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onespecialidad_idChanging(int value);
    partial void Onespecialidad_idChanged();
    partial void Onespecialidad_nombreChanging(string value);
    partial void Onespecialidad_nombreChanged();
    #endregion
		
		public Especialidade()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_especialidad_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int especialidad_id
		{
			get
			{
				return this._especialidad_id;
			}
			set
			{
				if ((this._especialidad_id != value))
				{
					this.Onespecialidad_idChanging(value);
					this.SendPropertyChanging();
					this._especialidad_id = value;
					this.SendPropertyChanged("especialidad_id");
					this.Onespecialidad_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_especialidad_nombre", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string especialidad_nombre
		{
			get
			{
				return this._especialidad_nombre;
			}
			set
			{
				if ((this._especialidad_nombre != value))
				{
					this.Onespecialidad_nombreChanging(value);
					this.SendPropertyChanging();
					this._especialidad_nombre = value;
					this.SendPropertyChanged("especialidad_nombre");
					this.Onespecialidad_nombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Turnos")]
	public partial class Turno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _turno_id;
		
		private System.Nullable<System.DateTime> _turno_sysdate;
		
		private System.DateTime _turno_fecha;
		
		private int _turno_paciente;
		
		private int _turno_medico;
		
		private int _turno_obraSocial;
		
		private int _turno_especialidad;
		
		private System.Nullable<int> _turno_primeraVez;
		
		private System.Nullable<int> _turno_telefono;
		
		private System.Nullable<int> _turno_nombre;
		
		private System.Nullable<int> _turno_tipo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onturno_idChanging(int value);
    partial void Onturno_idChanged();
    partial void Onturno_sysdateChanging(System.Nullable<System.DateTime> value);
    partial void Onturno_sysdateChanged();
    partial void Onturno_fechaChanging(System.DateTime value);
    partial void Onturno_fechaChanged();
    partial void Onturno_pacienteChanging(int value);
    partial void Onturno_pacienteChanged();
    partial void Onturno_medicoChanging(int value);
    partial void Onturno_medicoChanged();
    partial void Onturno_obraSocialChanging(int value);
    partial void Onturno_obraSocialChanged();
    partial void Onturno_especialidadChanging(int value);
    partial void Onturno_especialidadChanged();
    partial void Onturno_primeraVezChanging(System.Nullable<int> value);
    partial void Onturno_primeraVezChanged();
    partial void Onturno_telefonoChanging(System.Nullable<int> value);
    partial void Onturno_telefonoChanged();
    partial void Onturno_nombreChanging(System.Nullable<int> value);
    partial void Onturno_nombreChanged();
    partial void Onturno_tipoChanging(System.Nullable<int> value);
    partial void Onturno_tipoChanged();
    #endregion
		
		public Turno()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int turno_id
		{
			get
			{
				return this._turno_id;
			}
			set
			{
				if ((this._turno_id != value))
				{
					this.Onturno_idChanging(value);
					this.SendPropertyChanging();
					this._turno_id = value;
					this.SendPropertyChanged("turno_id");
					this.Onturno_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno_sysdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> turno_sysdate
		{
			get
			{
				return this._turno_sysdate;
			}
			set
			{
				if ((this._turno_sysdate != value))
				{
					this.Onturno_sysdateChanging(value);
					this.SendPropertyChanging();
					this._turno_sysdate = value;
					this.SendPropertyChanged("turno_sysdate");
					this.Onturno_sysdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime turno_fecha
		{
			get
			{
				return this._turno_fecha;
			}
			set
			{
				if ((this._turno_fecha != value))
				{
					this.Onturno_fechaChanging(value);
					this.SendPropertyChanging();
					this._turno_fecha = value;
					this.SendPropertyChanged("turno_fecha");
					this.Onturno_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno_paciente", DbType="Int NOT NULL")]
		public int turno_paciente
		{
			get
			{
				return this._turno_paciente;
			}
			set
			{
				if ((this._turno_paciente != value))
				{
					this.Onturno_pacienteChanging(value);
					this.SendPropertyChanging();
					this._turno_paciente = value;
					this.SendPropertyChanged("turno_paciente");
					this.Onturno_pacienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno_medico", DbType="Int NOT NULL")]
		public int turno_medico
		{
			get
			{
				return this._turno_medico;
			}
			set
			{
				if ((this._turno_medico != value))
				{
					this.Onturno_medicoChanging(value);
					this.SendPropertyChanging();
					this._turno_medico = value;
					this.SendPropertyChanged("turno_medico");
					this.Onturno_medicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno_obraSocial", DbType="Int NOT NULL")]
		public int turno_obraSocial
		{
			get
			{
				return this._turno_obraSocial;
			}
			set
			{
				if ((this._turno_obraSocial != value))
				{
					this.Onturno_obraSocialChanging(value);
					this.SendPropertyChanging();
					this._turno_obraSocial = value;
					this.SendPropertyChanged("turno_obraSocial");
					this.Onturno_obraSocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno_especialidad", DbType="Int NOT NULL")]
		public int turno_especialidad
		{
			get
			{
				return this._turno_especialidad;
			}
			set
			{
				if ((this._turno_especialidad != value))
				{
					this.Onturno_especialidadChanging(value);
					this.SendPropertyChanging();
					this._turno_especialidad = value;
					this.SendPropertyChanged("turno_especialidad");
					this.Onturno_especialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno_primeraVez", DbType="Int")]
		public System.Nullable<int> turno_primeraVez
		{
			get
			{
				return this._turno_primeraVez;
			}
			set
			{
				if ((this._turno_primeraVez != value))
				{
					this.Onturno_primeraVezChanging(value);
					this.SendPropertyChanging();
					this._turno_primeraVez = value;
					this.SendPropertyChanged("turno_primeraVez");
					this.Onturno_primeraVezChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno_telefono", DbType="Int")]
		public System.Nullable<int> turno_telefono
		{
			get
			{
				return this._turno_telefono;
			}
			set
			{
				if ((this._turno_telefono != value))
				{
					this.Onturno_telefonoChanging(value);
					this.SendPropertyChanging();
					this._turno_telefono = value;
					this.SendPropertyChanged("turno_telefono");
					this.Onturno_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno_nombre", DbType="Int")]
		public System.Nullable<int> turno_nombre
		{
			get
			{
				return this._turno_nombre;
			}
			set
			{
				if ((this._turno_nombre != value))
				{
					this.Onturno_nombreChanging(value);
					this.SendPropertyChanging();
					this._turno_nombre = value;
					this.SendPropertyChanged("turno_nombre");
					this.Onturno_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno_tipo", DbType="Int")]
		public System.Nullable<int> turno_tipo
		{
			get
			{
				return this._turno_tipo;
			}
			set
			{
				if ((this._turno_tipo != value))
				{
					this.Onturno_tipoChanging(value);
					this.SendPropertyChanging();
					this._turno_tipo = value;
					this.SendPropertyChanged("turno_tipo");
					this.Onturno_tipoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Especialidad-Medico]")]
	public partial class Especialidad_Medico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idEspecialidad;
		
		private int _idMedico;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidEspecialidadChanging(int value);
    partial void OnidEspecialidadChanged();
    partial void OnidMedicoChanging(int value);
    partial void OnidMedicoChanged();
    #endregion
		
		public Especialidad_Medico()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEspecialidad", DbType="Int NOT NULL")]
		public int idEspecialidad
		{
			get
			{
				return this._idEspecialidad;
			}
			set
			{
				if ((this._idEspecialidad != value))
				{
					this.OnidEspecialidadChanging(value);
					this.SendPropertyChanging();
					this._idEspecialidad = value;
					this.SendPropertyChanged("idEspecialidad");
					this.OnidEspecialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedico", DbType="Int NOT NULL")]
		public int idMedico
		{
			get
			{
				return this._idMedico;
			}
			set
			{
				if ((this._idMedico != value))
				{
					this.OnidMedicoChanging(value);
					this.SendPropertyChanging();
					this._idMedico = value;
					this.SendPropertyChanged("idMedico");
					this.OnidMedicoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Medicos")]
	public partial class Medico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _medico_id;
		
		private string _medico_nombre;
		
		private string _medico_apellido;
		
		private System.Nullable<int> _medico_DNI;
		
		private System.Nullable<int> _medico_telefono;
		
		private string _medico_mail;

        public override string ToString()
        {
            return this._medico_apellido + ", " + this._medico_nombre;
        }
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmedico_idChanging(int value);
    partial void Onmedico_idChanged();
    partial void Onmedico_nombreChanging(string value);
    partial void Onmedico_nombreChanged();
    partial void Onmedico_apellidoChanging(string value);
    partial void Onmedico_apellidoChanged();
    partial void Onmedico_DNIChanging(System.Nullable<int> value);
    partial void Onmedico_DNIChanged();
    partial void Onmedico_telefonoChanging(System.Nullable<int> value);
    partial void Onmedico_telefonoChanged();
    partial void Onmedico_mailChanging(string value);
    partial void Onmedico_mailChanged();
    #endregion
		
		public Medico()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medico_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int medico_id
		{
			get
			{
				return this._medico_id;
			}
			set
			{
				if ((this._medico_id != value))
				{
					this.Onmedico_idChanging(value);
					this.SendPropertyChanging();
					this._medico_id = value;
					this.SendPropertyChanged("medico_id");
					this.Onmedico_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medico_nombre", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string medico_nombre
		{
			get
			{
				return this._medico_nombre;
			}
			set
			{
				if ((this._medico_nombre != value))
				{
					this.Onmedico_nombreChanging(value);
					this.SendPropertyChanging();
					this._medico_nombre = value;
					this.SendPropertyChanged("medico_nombre");
					this.Onmedico_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medico_apellido", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string medico_apellido
		{
			get
			{
				return this._medico_apellido;
			}
			set
			{
				if ((this._medico_apellido != value))
				{
					this.Onmedico_apellidoChanging(value);
					this.SendPropertyChanging();
					this._medico_apellido = value;
					this.SendPropertyChanged("medico_apellido");
					this.Onmedico_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medico_DNI", DbType="Int")]
		public System.Nullable<int> medico_DNI
		{
			get
			{
				return this._medico_DNI;
			}
			set
			{
				if ((this._medico_DNI != value))
				{
					this.Onmedico_DNIChanging(value);
					this.SendPropertyChanging();
					this._medico_DNI = value;
					this.SendPropertyChanged("medico_DNI");
					this.Onmedico_DNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medico_telefono", DbType="Int")]
		public System.Nullable<int> medico_telefono
		{
			get
			{
				return this._medico_telefono;
			}
			set
			{
				if ((this._medico_telefono != value))
				{
					this.Onmedico_telefonoChanging(value);
					this.SendPropertyChanging();
					this._medico_telefono = value;
					this.SendPropertyChanged("medico_telefono");
					this.Onmedico_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medico_mail", DbType="VarChar(200)")]
		public string medico_mail
		{
			get
			{
				return this._medico_mail;
			}
			set
			{
				if ((this._medico_mail != value))
				{
					this.Onmedico_mailChanging(value);
					this.SendPropertyChanging();
					this._medico_mail = value;
					this.SendPropertyChanged("medico_mail");
					this.Onmedico_mailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MedicoxDia")]
	public partial class MedicoxDia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idMedicoxDia;
		
		private int _idMedico;
		
		private int _idEspecialidad;
		
		private int _dia;
		
		private int _horaInicio;
		
		private int _horaFin;
		
		private int _duracionTurno;
		
		private int _frecuencia;
		
		private int _inicioFrecuencia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMedicoxDiaChanging(int value);
    partial void OnidMedicoxDiaChanged();
    partial void OnidMedicoChanging(int value);
    partial void OnidMedicoChanged();
    partial void OnidEspecialidadChanging(int value);
    partial void OnidEspecialidadChanged();
    partial void OndiaChanging(int value);
    partial void OndiaChanged();
    partial void OnhoraInicioChanging(int value);
    partial void OnhoraInicioChanged();
    partial void OnhoraFinChanging(int value);
    partial void OnhoraFinChanged();
    partial void OnduracionTurnoChanging(int value);
    partial void OnduracionTurnoChanged();
    partial void OnfrecuenciaChanging(int value);
    partial void OnfrecuenciaChanged();
    partial void OninicioFrecuenciaChanging(int value);
    partial void OninicioFrecuenciaChanged();
    #endregion
		
		public MedicoxDia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedicoxDia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idMedicoxDia
		{
			get
			{
				return this._idMedicoxDia;
			}
			set
			{
				if ((this._idMedicoxDia != value))
				{
					this.OnidMedicoxDiaChanging(value);
					this.SendPropertyChanging();
					this._idMedicoxDia = value;
					this.SendPropertyChanged("idMedicoxDia");
					this.OnidMedicoxDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMedico", DbType="Int NOT NULL")]
		public int idMedico
		{
			get
			{
				return this._idMedico;
			}
			set
			{
				if ((this._idMedico != value))
				{
					this.OnidMedicoChanging(value);
					this.SendPropertyChanging();
					this._idMedico = value;
					this.SendPropertyChanged("idMedico");
					this.OnidMedicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEspecialidad", DbType="Int NOT NULL")]
		public int idEspecialidad
		{
			get
			{
				return this._idEspecialidad;
			}
			set
			{
				if ((this._idEspecialidad != value))
				{
					this.OnidEspecialidadChanging(value);
					this.SendPropertyChanging();
					this._idEspecialidad = value;
					this.SendPropertyChanged("idEspecialidad");
					this.OnidEspecialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia", DbType="Int NOT NULL")]
		public int dia
		{
			get
			{
				return this._dia;
			}
			set
			{
				if ((this._dia != value))
				{
					this.OndiaChanging(value);
					this.SendPropertyChanging();
					this._dia = value;
					this.SendPropertyChanged("dia");
					this.OndiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horaInicio", DbType="Int NOT NULL")]
		public int horaInicio
		{
			get
			{
				return this._horaInicio;
			}
			set
			{
				if ((this._horaInicio != value))
				{
					this.OnhoraInicioChanging(value);
					this.SendPropertyChanging();
					this._horaInicio = value;
					this.SendPropertyChanged("horaInicio");
					this.OnhoraInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horaFin", DbType="Int NOT NULL")]
		public int horaFin
		{
			get
			{
				return this._horaFin;
			}
			set
			{
				if ((this._horaFin != value))
				{
					this.OnhoraFinChanging(value);
					this.SendPropertyChanging();
					this._horaFin = value;
					this.SendPropertyChanged("horaFin");
					this.OnhoraFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duracionTurno", DbType="Int NOT NULL")]
		public int duracionTurno
		{
			get
			{
				return this._duracionTurno;
			}
			set
			{
				if ((this._duracionTurno != value))
				{
					this.OnduracionTurnoChanging(value);
					this.SendPropertyChanging();
					this._duracionTurno = value;
					this.SendPropertyChanged("duracionTurno");
					this.OnduracionTurnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frecuencia", DbType="Int NOT NULL")]
		public int frecuencia
		{
			get
			{
				return this._frecuencia;
			}
			set
			{
				if ((this._frecuencia != value))
				{
					this.OnfrecuenciaChanging(value);
					this.SendPropertyChanging();
					this._frecuencia = value;
					this.SendPropertyChanged("frecuencia");
					this.OnfrecuenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inicioFrecuencia", DbType="Int NOT NULL")]
		public int inicioFrecuencia
		{
			get
			{
				return this._inicioFrecuencia;
			}
			set
			{
				if ((this._inicioFrecuencia != value))
				{
					this.OninicioFrecuenciaChanging(value);
					this.SendPropertyChanging();
					this._inicioFrecuencia = value;
					this.SendPropertyChanged("inicioFrecuencia");
					this.OninicioFrecuenciaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ObraSocial_TipoTurno")]
	public partial class ObraSocial_TipoTurno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _obraSocial;
		
		private int _tipoTurno;
		
		private string _covertura;
		
		private string _observaciones;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnobraSocialChanging(int value);
    partial void OnobraSocialChanged();
    partial void OntipoTurnoChanging(int value);
    partial void OntipoTurnoChanged();
    partial void OncoverturaChanging(string value);
    partial void OncoverturaChanged();
    partial void OnobservacionesChanging(string value);
    partial void OnobservacionesChanged();
    #endregion
		
		public ObraSocial_TipoTurno()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obraSocial", DbType="Int NOT NULL")]
		public int obraSocial
		{
			get
			{
				return this._obraSocial;
			}
			set
			{
				if ((this._obraSocial != value))
				{
					this.OnobraSocialChanging(value);
					this.SendPropertyChanging();
					this._obraSocial = value;
					this.SendPropertyChanged("obraSocial");
					this.OnobraSocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoTurno", DbType="Int NOT NULL")]
		public int tipoTurno
		{
			get
			{
				return this._tipoTurno;
			}
			set
			{
				if ((this._tipoTurno != value))
				{
					this.OntipoTurnoChanging(value);
					this.SendPropertyChanging();
					this._tipoTurno = value;
					this.SendPropertyChanged("tipoTurno");
					this.OntipoTurnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_covertura", DbType="VarChar(200)")]
		public string covertura
		{
			get
			{
				return this._covertura;
			}
			set
			{
				if ((this._covertura != value))
				{
					this.OncoverturaChanging(value);
					this.SendPropertyChanging();
					this._covertura = value;
					this.SendPropertyChanged("covertura");
					this.OncoverturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observaciones", DbType="VarChar(2000)")]
		public string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				if ((this._observaciones != value))
				{
					this.OnobservacionesChanging(value);
					this.SendPropertyChanging();
					this._observaciones = value;
					this.SendPropertyChanged("observaciones");
					this.OnobservacionesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ObrasSociales")]
	public partial class ObrasSociale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _obra_id;
		
		private string _obra_nombre;
		
		private string _obra_mail;
		
		private System.Nullable<int> _obra_telefono;
		
		private string _obra_direccion;
		
		private string _obra_localidad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onobra_idChanging(int value);
    partial void Onobra_idChanged();
    partial void Onobra_nombreChanging(string value);
    partial void Onobra_nombreChanged();
    partial void Onobra_mailChanging(string value);
    partial void Onobra_mailChanged();
    partial void Onobra_telefonoChanging(System.Nullable<int> value);
    partial void Onobra_telefonoChanged();
    partial void Onobra_direccionChanging(string value);
    partial void Onobra_direccionChanged();
    partial void Onobra_localidadChanging(string value);
    partial void Onobra_localidadChanged();
    #endregion
		
		public ObrasSociale()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obra_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int obra_id
		{
			get
			{
				return this._obra_id;
			}
			set
			{
				if ((this._obra_id != value))
				{
					this.Onobra_idChanging(value);
					this.SendPropertyChanging();
					this._obra_id = value;
					this.SendPropertyChanged("obra_id");
					this.Onobra_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obra_nombre", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string obra_nombre
		{
			get
			{
				return this._obra_nombre;
			}
			set
			{
				if ((this._obra_nombre != value))
				{
					this.Onobra_nombreChanging(value);
					this.SendPropertyChanging();
					this._obra_nombre = value;
					this.SendPropertyChanged("obra_nombre");
					this.Onobra_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obra_mail", DbType="VarChar(200)")]
		public string obra_mail
		{
			get
			{
				return this._obra_mail;
			}
			set
			{
				if ((this._obra_mail != value))
				{
					this.Onobra_mailChanging(value);
					this.SendPropertyChanging();
					this._obra_mail = value;
					this.SendPropertyChanged("obra_mail");
					this.Onobra_mailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obra_telefono", DbType="Int")]
		public System.Nullable<int> obra_telefono
		{
			get
			{
				return this._obra_telefono;
			}
			set
			{
				if ((this._obra_telefono != value))
				{
					this.Onobra_telefonoChanging(value);
					this.SendPropertyChanging();
					this._obra_telefono = value;
					this.SendPropertyChanged("obra_telefono");
					this.Onobra_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obra_direccion", DbType="VarChar(200)")]
		public string obra_direccion
		{
			get
			{
				return this._obra_direccion;
			}
			set
			{
				if ((this._obra_direccion != value))
				{
					this.Onobra_direccionChanging(value);
					this.SendPropertyChanging();
					this._obra_direccion = value;
					this.SendPropertyChanged("obra_direccion");
					this.Onobra_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obra_localidad", DbType="VarChar(200)")]
		public string obra_localidad
		{
			get
			{
				return this._obra_localidad;
			}
			set
			{
				if ((this._obra_localidad != value))
				{
					this.Onobra_localidadChanging(value);
					this.SendPropertyChanging();
					this._obra_localidad = value;
					this.SendPropertyChanged("obra_localidad");
					this.Onobra_localidadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pacientes")]
	public partial class Paciente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _paciente_id;
		
		private string _paciente_nombre;
		
		private string _paciente_apellido;
		
		private int _paciente_dni;
		
		private System.Nullable<int> _paciente_tel;
		
		private System.Nullable<int> _paciente_cel;
		
		private string _paciente_mail;
		
		private string _paciente_direccion;
		
		private string _paciente_localidad;
		
		private System.Nullable<System.DateTime> _paciente_fechaAlta;
		
		private string _paciente_observaciones;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpaciente_idChanging(int value);
    partial void Onpaciente_idChanged();
    partial void Onpaciente_nombreChanging(string value);
    partial void Onpaciente_nombreChanged();
    partial void Onpaciente_apellidoChanging(string value);
    partial void Onpaciente_apellidoChanged();
    partial void Onpaciente_dniChanging(int value);
    partial void Onpaciente_dniChanged();
    partial void Onpaciente_telChanging(System.Nullable<int> value);
    partial void Onpaciente_telChanged();
    partial void Onpaciente_celChanging(System.Nullable<int> value);
    partial void Onpaciente_celChanged();
    partial void Onpaciente_mailChanging(string value);
    partial void Onpaciente_mailChanged();
    partial void Onpaciente_direccionChanging(string value);
    partial void Onpaciente_direccionChanged();
    partial void Onpaciente_localidadChanging(string value);
    partial void Onpaciente_localidadChanged();
    partial void Onpaciente_fechaAltaChanging(System.Nullable<System.DateTime> value);
    partial void Onpaciente_fechaAltaChanged();
    partial void Onpaciente_observacionesChanging(string value);
    partial void Onpaciente_observacionesChanged();
    #endregion
		
		public Paciente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paciente_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int paciente_id
		{
			get
			{
				return this._paciente_id;
			}
			set
			{
				if ((this._paciente_id != value))
				{
					this.Onpaciente_idChanging(value);
					this.SendPropertyChanging();
					this._paciente_id = value;
					this.SendPropertyChanged("paciente_id");
					this.Onpaciente_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paciente_nombre", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string paciente_nombre
		{
			get
			{
				return this._paciente_nombre;
			}
			set
			{
				if ((this._paciente_nombre != value))
				{
					this.Onpaciente_nombreChanging(value);
					this.SendPropertyChanging();
					this._paciente_nombre = value;
					this.SendPropertyChanged("paciente_nombre");
					this.Onpaciente_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paciente_apellido", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string paciente_apellido
		{
			get
			{
				return this._paciente_apellido;
			}
			set
			{
				if ((this._paciente_apellido != value))
				{
					this.Onpaciente_apellidoChanging(value);
					this.SendPropertyChanging();
					this._paciente_apellido = value;
					this.SendPropertyChanged("paciente_apellido");
					this.Onpaciente_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paciente_dni", DbType="Int NOT NULL")]
		public int paciente_dni
		{
			get
			{
				return this._paciente_dni;
			}
			set
			{
				if ((this._paciente_dni != value))
				{
					this.Onpaciente_dniChanging(value);
					this.SendPropertyChanging();
					this._paciente_dni = value;
					this.SendPropertyChanged("paciente_dni");
					this.Onpaciente_dniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paciente_tel", DbType="Int")]
		public System.Nullable<int> paciente_tel
		{
			get
			{
				return this._paciente_tel;
			}
			set
			{
				if ((this._paciente_tel != value))
				{
					this.Onpaciente_telChanging(value);
					this.SendPropertyChanging();
					this._paciente_tel = value;
					this.SendPropertyChanged("paciente_tel");
					this.Onpaciente_telChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paciente_cel", DbType="Int")]
		public System.Nullable<int> paciente_cel
		{
			get
			{
				return this._paciente_cel;
			}
			set
			{
				if ((this._paciente_cel != value))
				{
					this.Onpaciente_celChanging(value);
					this.SendPropertyChanging();
					this._paciente_cel = value;
					this.SendPropertyChanged("paciente_cel");
					this.Onpaciente_celChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paciente_mail", DbType="VarChar(200)")]
		public string paciente_mail
		{
			get
			{
				return this._paciente_mail;
			}
			set
			{
				if ((this._paciente_mail != value))
				{
					this.Onpaciente_mailChanging(value);
					this.SendPropertyChanging();
					this._paciente_mail = value;
					this.SendPropertyChanged("paciente_mail");
					this.Onpaciente_mailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paciente_direccion", DbType="VarChar(200)")]
		public string paciente_direccion
		{
			get
			{
				return this._paciente_direccion;
			}
			set
			{
				if ((this._paciente_direccion != value))
				{
					this.Onpaciente_direccionChanging(value);
					this.SendPropertyChanging();
					this._paciente_direccion = value;
					this.SendPropertyChanged("paciente_direccion");
					this.Onpaciente_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paciente_localidad", DbType="VarChar(200)")]
		public string paciente_localidad
		{
			get
			{
				return this._paciente_localidad;
			}
			set
			{
				if ((this._paciente_localidad != value))
				{
					this.Onpaciente_localidadChanging(value);
					this.SendPropertyChanging();
					this._paciente_localidad = value;
					this.SendPropertyChanged("paciente_localidad");
					this.Onpaciente_localidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paciente_fechaAlta", DbType="DateTime")]
		public System.Nullable<System.DateTime> paciente_fechaAlta
		{
			get
			{
				return this._paciente_fechaAlta;
			}
			set
			{
				if ((this._paciente_fechaAlta != value))
				{
					this.Onpaciente_fechaAltaChanging(value);
					this.SendPropertyChanging();
					this._paciente_fechaAlta = value;
					this.SendPropertyChanged("paciente_fechaAlta");
					this.Onpaciente_fechaAltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paciente_observaciones", DbType="VarChar(2000)")]
		public string paciente_observaciones
		{
			get
			{
				return this._paciente_observaciones;
			}
			set
			{
				if ((this._paciente_observaciones != value))
				{
					this.Onpaciente_observacionesChanging(value);
					this.SendPropertyChanging();
					this._paciente_observaciones = value;
					this.SendPropertyChanged("paciente_observaciones");
					this.Onpaciente_observacionesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoTurnos")]
	public partial class TipoTurno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipoTurno;
		
		private string _Nombre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipoTurnoChanging(int value);
    partial void OnidTipoTurnoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public TipoTurno()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoTurno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTipoTurno
		{
			get
			{
				return this._idTipoTurno;
			}
			set
			{
				if ((this._idTipoTurno != value))
				{
					this.OnidTipoTurnoChanging(value);
					this.SendPropertyChanging();
					this._idTipoTurno = value;
					this.SendPropertyChanged("idTipoTurno");
					this.OnidTipoTurnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
